authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, PasswordChangeView
from . import views

app_name = 'authentication'
urlpatterns = [
    path('', LoginView.as_view(template_name='authentication/connexion.html',
         redirect_authenticated_user=True), name='connexion'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authentication/password_change.html',
        success_url='done/'), name='password_change'),
    path('password_change/done/', views.password_changed,
         name='password_change_done'),
    path("inscription/", views.inscription, name="inscription"),
    path("user_picture/", views.user_picture, name="user_picture"),
    path('deconnexion/', views.deconnexion, name="deconnexion"),
]

litreview_project/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include("review.urls", namespace='review')),
    path('', include("authentication.urls", namespace='authentication')),
]

review/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'review'
urlpatterns = [
    path('home/', views.flux, name='home'),
    path('create_new_review/', views.create_new_review,
         name='create_new_review'),
    path('create_new_ticket/', views.create_new_ticket,
         name='create_new_ticket'),
    path('create_new_review_for_ticket/<int:number_ticket>/',
         views.create_new_review_for_ticket,
         name='create_new_review_for_ticket'),
    path('create_new_ticket_and_review/',
         views.create_new_ticket_and_review,
         name='create_new_ticket_and_review'),

    path('delete_ticket/<int:number_ticket>/',
         views.delete_ticket, name='delete_ticket'),
    path('modify_ticket/<int:number_ticket>/',
         views.modify_ticket, name='modify_ticket'),
    path('ticket/<int:number_ticket>/', views.read_ticket, name='read_ticket'),

    path('delete_review/<int:number_review>/',
         views.delete_review, name='delete_review'),
    path('modify_review/<int:number_review>/',
         views.modify_review, name='modify_review'),

    path('flux/', views.flux, name='flux'),
    path('follow/', views.follow, name='follow'),
    path('posts/', views.posts, name='posts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

review/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models
from django.utils import timezone
from PIL import Image


class Ticket(models.Model):
    title = models.CharField(max_length=128, verbose_name="Titre du Ticket")
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    time_created = models.DateTimeField(
        default=timezone.now)

    IMAGE_MAX_SIZE = (300, 300)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            self.resize_image()


class Review(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        verbose_name="Note", help_text="Note attribuée à la critique")
    headline = models.CharField(
        max_length=128,
        verbose_name="Titre de Critique")
    body = models.TextField(max_length=8192, blank=True,
                            verbose_name="Commentaire")
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(
        default=timezone.now)


class UserFollows(models.Model):
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name="following")
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name="followed_by")

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = ('user', 'followed_user')

review/forms.py
from django import forms

from . import models as models_review


class TicketForm(forms.ModelForm):
    title = forms.CharField(label="Titre", widget=forms.TextInput(
        {"class": "form-control", "placeholder": "Mettez le titre du livre"}))
    description = forms.CharField(label="Description", widget=forms.Textarea(
        {"class": "form-control", "placeholder": "Mettez le titre du livre"}))

    class Meta:
        model = models_review.Ticket
        fields = ['title', 'description', 'image']


class ModifTicketTitleDescription(forms.ModelForm):
    title = forms.CharField(label="Titre", widget=forms.TextInput(
        {"class": "form-control", "placeholder": "Mettez le titre du livre"}))
    description = forms.CharField(label="Description", widget=forms.Textarea(
        {"class": "form-control", "placeholder": "Mettez le titre du livre"}))

    class Meta:
        model = models_review.Ticket
        fields = ['title', 'description']


class ModifPicture(forms.ModelForm):

    class Meta:
        model = models_review.Ticket
        fields = ['image']


class ReviewForm(forms.ModelForm):

    headline = forms.CharField(label="Titre de la critique",
                               widget=forms.TextInput(
                                {"class": "form-control",
                                 "placeholder": "Mettez le titre de votre "
                                                "critique"}
                               )
                               )
    RATING_CHOICES = [(0, "-0"), (1, '- 1'), (2, '-2'),
                      (3, '-3'), (4, '-4'), (5, '-5')]
    rating = forms.ChoiceField(
        choices=RATING_CHOICES, widget=forms.RadioSelect, label="Votre note")
    body = forms.CharField(label="Votre critique", widget=forms.Textarea(
        {"class": "form-control",
         "placeholder": "Mettez le détails de votre critique"}))

    class Meta:
        model = models_review.Review
        fields = ["headline", 'rating', 'body']


class UserFollowsForm(forms.ModelForm):
    class Meta:
        model = models_review.UserFollows
        fields = ["user"]


class UserRemoveFollowsForm(forms.ModelForm):
    class Meta:
        model = models_review.UserFollows
        fields = ["user"]

review/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required


from . import forms, models
from authentication import models as auth_models


@login_required
def create_new_ticket(request):
    form = forms.TicketForm()
    if request.method == 'POST':
        form = forms.TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect('review:flux')
    context = {'form': form}
    return render(request, 'review/create_new_ticket.html', context)


@login_required
def create_new_ticket_and_review(request):
    ticket_form = forms.TicketForm()
    review_form = forms.ReviewForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        review_form = forms.ReviewForm(request.POST)
        if all([ticket_form.is_valid(), review_form.is_valid()]):
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            review = review_form.save(commit=False)
            review.ticket_id = ticket.id
            review.user = request.user
            review.save()
            return redirect('review:flux')
    context = {'ticket_form': ticket_form, "review_form": review_form}
    return render(request, 'review/create_new_ticket_and_review.html', context)


@login_required
def create_new_review_for_ticket(request, number_ticket):
    tickets = models.Ticket.objects.filter(id=number_ticket)
    form = forms.ReviewForm()
    if request.method == 'POST':
        form = forms.ReviewForm(
            request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user_id = request.user.id
            review.ticket_id = number_ticket
            review.save()
            return redirect('review:flux')
    context = {'form': form, "tickets": tickets}
    return render(request, 'review/create_new_review.html', context)


@login_required
def create_new_review(request):
    return render(request, 'review/create_new_review.html')


@login_required
def follow(request):
    all_followed_id = list(models.UserFollows.objects.filter(
        user=request.user.id).values_list('followed_user_id', flat=True))
    all_followed_id.append(request.user.id)
    all_users_to_be_followed = auth_models.User.objects.all().exclude(
        id__in=all_followed_id)
    user_form = forms.UserFollowsForm()
    remove_user_followed_form = forms.UserRemoveFollowsForm()
    user_followed_by_request_user = models.UserFollows.objects.filter(
        user=request.user.id)
    request_user_followed_by_other = models.UserFollows.objects.filter(
        followed_user=request.user.id)
    context = {"user_form": user_form,
               "remove_user_followed_form": remove_user_followed_form,
               "all_users_to_be_followed": all_users_to_be_followed,
               "user_followed_by_request_user": user_followed_by_request_user,
               "request_user_followed_by_other": request_user_followed_by_other
               }

    if request.method == 'POST':
        user_form = forms.UserFollowsForm(request.POST)
        remove_user_followed_form = forms.UserRemoveFollowsForm(request.POST)
        if user_form.is_valid():
            follow = models.UserFollows.objects.filter(
                user_id=request.user.id,
                followed_user=request.POST.get("user")[0])
            if not follow:
                follow = models.UserFollows.objects.create()
                follow.user_id = request.user.id
                follow.followed_user_id = str(request.POST.get("user")[0])
                follow.save()

        if request.POST.get("user_followed_to_delete"):
            followed = models.UserFollows.objects.filter(
                user_id=request.user.id,
                followed_user=request.POST.get("user_followed_to_delete")[0])
            followed.delete()
        return redirect("review:follow")
    return render(request, 'review/follow.html', context)


@ login_required
def flux(request):
    all_followed = models.UserFollows.objects.filter(
        user_id=request.user.id).values_list('followed_user_id', flat=True)
    all_followed = list(all_followed)
    all_followed.append(request.user.id)

    reviews = models.Review.objects.filter(
        user_id__in=all_followed)
    reviews_link_tickets = models.Review.objects.filter(
        user_id__in=all_followed).values_list('ticket_id', flat=True)
    tickets = models.Ticket.objects.filter(
        user_id__in=all_followed) | models.Ticket.objects.filter(
        id__in=reviews_link_tickets)
    tickets = tickets.order_by("-id")
    context = {"tickets": tickets, "reviews": reviews,
               "reviews_link_tickets": reviews_link_tickets}
    return render(request, 'review/flux.html', context=context)


@ login_required
def posts(request):
    reviews = models.Review.objects.filter(
        user_id=request.user.id).values()
    reviews_link_tickets = models.Review.objects.filter(
        user_id=request.user.id).values_list('ticket_id', flat=True)
    tickets = models.Ticket.objects.filter(
        user_id=request.user.id) | models.Ticket.objects.filter(
        id__in=reviews_link_tickets)
    tickets = tickets.order_by("-id")
    context = {"tickets": tickets, "reviews": reviews,
               "reviews_link_tickets": reviews_link_tickets}
    return render(request, 'review/posts.html', context)
# GESTION TICKETS


@ login_required
def modify_ticket(request, number_ticket):
    context = {"number_ticket": number_ticket}
    tickets = get_object_or_404(models.Ticket, id=number_ticket)
    if request.user.id == tickets.user_id:
        form = forms.ModifTicketTitleDescription(instance=tickets)
        context["form"] = form
        picture = forms.ModifPicture(instance=tickets)
        context["picture"] = picture
        context["tickets"] = tickets
        if request.method == 'POST':
            form = forms.ModifTicketTitleDescription(
                request.POST)
            if form.is_valid():
                tickets.title = form.cleaned_data["title"]
                tickets.description = form.cleaned_data["description"]
                tickets.save()

                picture = forms.ModifPicture(request.POST, request.FILES)
                if all([picture.is_valid()]):
                    new_picture = picture.save(commit=False)
                    tickets.image = new_picture.image
                    tickets.save()
                return redirect('review:posts')

    return render(request, 'review/modify_ticket.html', context)


@ login_required
def read_ticket(request, number_ticket):
    ticket = get_object_or_404(models.Ticket, id=number_ticket)
    context = {"ticket": ticket, "number_ticket": number_ticket}
    review = models.Review.objects.filter(ticket_id=number_ticket)
    if review:
        ticket.review = review[0]
        context["review"] = review[0]
    return render(request, 'review/read_ticket.html', context)


@ login_required
def delete_ticket(request, number_ticket):
    context = {"number_ticket": number_ticket}
    ticket = get_object_or_404(models.Ticket, id=number_ticket)
    if ticket:
        context["ticket"] = ticket
    review = models.Review.objects.filter(ticket_id=number_ticket)
    if review:
        context["review"] = review

    if request.method == 'POST':
        ticket = get_object_or_404(
            models.Ticket, id=number_ticket)
        review = models.Review.objects.filter(ticket_id=number_ticket)
        if review:
            review.delete()
        if ticket:
            ticket.delete()
        return redirect("review:posts")
    return render(request, 'review/delete_ticket.html', context)


# GESTION REVIEW


@ login_required
def modify_review(request, number_review):
    context = {"number_review": number_review}
    reviews = get_object_or_404(models.Review, id=number_review)
    ticket = get_object_or_404(models.Ticket, id=reviews.ticket_id)
    if request.user.id == reviews.user_id:
        form = forms.ReviewForm(instance=reviews)
        if request.method == 'POST':
            form = forms.ReviewForm(
                request.POST, instance=reviews)
            if form.is_valid():
                form.save()
                return redirect('review:flux')
        context["form"] = form
        if ticket:
            context["ticket"] = ticket
        if reviews:
            context["reviews"] = reviews
    return render(request, 'review/modify_review.html', context)


@ login_required
def delete_review(request, number_review):
    review = get_object_or_404(models.Review, id=number_review)
    ticket = get_object_or_404(models.Ticket, id=review.ticket_id)
    ticket.review = review
    if request.method == 'POST':
        review = get_object_or_404(models.Review, id=number_review)
        review.delete()
        return redirect("review:posts")
    context = {"review": review, "ticket": ticket}
    return render(request, 'review/delete_review.html', context)

review/templates/review/create_new_ticket.html
{% extends '_base.html' %} {% load static %} {% block main_content %}

<div class="container col-12 col-md-9 col-lg-6 p-2 borderTitle bg-light">
  <div class="row">
    <div class="text-center">
      <h1>LITReview - Creation d'un nouveau Ticket</h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="my-4 d-flex flex-row justify-content-center">
      <div class="col-12 col-md-10 col-lg-8 borderLeft">
        <h2 class="text-center m-3">Merci de remplir les champs requis, svp</h2>
        <div class="m-auto p-3">
          {% if form.errors %} {{ form.errors }} {% endif %}
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">{{form.as_p}}</div>
            <hr />
            <div class="text-center">
              <button class="btn btn-outline-danger" type="submit">
                <a
                  href="{% url 'review:flux' %}"
                  style="color: inherit; text-decoration: none"
                  >Retour</a
                >
              </button>
              <button class="btn btn-outline-success" type="submit">
                Envoyer la demande
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock main_content %}

review/templates/review/flux.html
{% extends '_base.html' %} {% load static %}
<!-- Page Home-->

{% block main_content %}
<style>
  body {
    background-image: url("{% static 'review/img/typewriter-801921_1920.jpg' %}");
    background-attachment: fixed;
    background-repeat: no-repeat;
    background-size: cover;
  }
</style>
<div
  class="container col-12 col-md-9 col-lg-6 m-auto p-2 shadow-lg borderTitle"
>
  <div class="column">
    <div class="jumbotron text-center">
      <h1>LITReview - Flux</h1>
    </div>
    <div class="d-flex flex-row justify-content-center">
      <a
        style="text-decoration: none"
        href="{% url 'review:create_new_ticket' %}"
        class="btn btn-outline-primary m-auto"
        >Demander une Critique</a
      >
      <a
        style="text-decoration: none"
        href="{% url 'review:create_new_ticket_and_review' %}"
        class="btn btn-outline-success m-auto"
        >Créer une Critique</a
      >
    </div>
  </div>
</div>

<div class="container">
  <div class="row col-12 d-flex flex-row justify-content-around">
    <div class="col-sm-12 col-md-9 m-2 p-3">
      {% for ticket in tickets %}

      <!--if critique associé au ticket-->
      {% if ticket.id in reviews_link_tickets%} 
        {% for review in reviews%}
          {% if ticket.id == review.ticket_id %}
      <div class="border border-success border-3 p-4 m-3 bg-light borderLeft">
            {% if review.user_id == request.user.id %}
              <p>Vous avez publié une critique</p>
              {% else %}
              <p>{{review.user}} a publié une critique</p>
            {% endif %}
            <p class="text-end">Date de demande : {{review.time_created}}</p>
            <h3 class="text-success">
              {{ review.headline }} - 
              {% if review.rating == 0 %} 
              {% elif review.rating == 1 %}⭐️
              {% elif review.rating == 2 %}⭐️⭐️
              {% elif review.rating == 3 %}⭐️⭐️⭐️
              {% elif review.rating == 4 %}⭐️⭐️⭐️⭐️
              {% elif review.rating == 5 %}⭐️⭐️⭐️⭐️⭐️{% endif %}
            </h3>
            <p>{{review.body}}</p>
          {% endif %}
        {% endfor %}

        <div class="border border-primary border-3 p-4 m-3">
          {% if ticket.user_id == request.user.id %}
            <p>Vous avez demandé une critique</p>
            {% else %}
            <p>{{ticket.user}} a demandé une critique</p>
          {% endif %}
          <a
            href="{% url 'review:read_ticket' ticket.id %}"
            style="color: inherit; text-decoration: none"
          >
            <h3 class="text-primary">
              Ticket #{{ ticket.id }} : {{ ticket.title }}
            </h3></a
          >
          <p class="text-end">Date de demande : {{ticket.time_created}}</p>

          {% if ticket.image %}
            <img src="{% get_media_prefix %}{{ ticket.image}}" width="200px" />
          {% endif %}
          <p>{{ ticket.description }}</p>
        </div>
      </div>
      {% else %}
      <div class="border border-primary border-3 p-4 m-3 bg-light borderLeft">
        {% if ticket.user_id == request.user.id %}
        <p>Vous avez demandé une critique</p>
        {% else %}
        <p>{{ticket.user}} a demandé une critique</p>
        {% endif%}
        <a
          href="{% url 'review:read_ticket' ticket.id %}"
          style="color: inherit; text-decoration: none"
        >
          <h3 class="text-primary">
            Ticket #{{ ticket.id }} : {{ ticket.title }}
          </h3></a
        >
        <p class="text-end">Date de demande : {{ticket.time_created}}</p>

        {% if ticket.image%}
        <img src="{% get_media_prefix %}{{ ticket.image}}" width="200px" />

        {% endif %}
        <p>{{ ticket.description }}</p>

        <div class="text-end">
          <button class="btn btn-outline-success">
            <a
              href="{% url 'review:create_new_review_for_ticket' ticket.id %}"
              style="color: inherit; text-decoration: none"
              >Créer une critique</a
            >
          </button>
        </div>
      </div>
      {% endif %}{% endfor %}
    </div>
  </div>
</div>
{% endblock main_content %}

review/templates/review/modify_ticket.html
{% extends '_base.html' %} {% load static %} {% block main_content %}
<div class="container col-12 col-md-9 col-lg-6 p-2 borderTitle bg-light">
  <div class="row">
    <div class="text-center">
      <h1>LITReview - Modifier votre Ticket</h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="my-4 d-flex flex-row justify-content-center">
      <div class="col-12 col-md-10 col-lg-8 borderLeft">
        {% if tickets%}
        <h2 class="text-center m-3">Merci de remplir les champs requis, svp</h2>
        {% endif %} {% if request.user.id != tickets.user_id %}
        <h2 class="text-center m-3">
          Vous n'etes pas le créateur du Ticket,<br />
          vous ne pouvez pas le modifier !
        </h2>
        <div class="text-center">
          <button class="btn btn-outline-danger">
            <a
              href="{% url 'review:posts' %}"
              style="color: inherit; text-decoration: none"
              >Retour</a
            >
          </button>
        </div>
        {% else %}
        <div class="m-auto p-3">
          {% if form.errors %} {{ form.errors }} {% endif %}
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group m-2 p-2">
              <label for="id_title">Titre de la demande : </label>
              <input
                type="text"
                name="title"
                maxlength="128"
                id="id_title"
                value="{{tickets.title}}"
                placeholder="Votre titre"
                required
              />
            </div>

            <div class="form-group m-2 p-2">
              <label for="id_description"
                >Description de votre demande :
              </label>
              <textarea
                name="description"
                rows="5"
                maxlength="2048"
                id="id_description"
                required
                class="col-10"
              >
                {{tickets.description}}</textarea
              >
            </div>

            <div class="form-group m-2 p-2">
              {% if tickets.image %}
              <p>Image Actuelle :</p>
              <img
                src="{% get_media_prefix %}{{tickets.image}}"
                alt="{{tickets.title}}"
                width="300px"
              />
              <br />
              {% endif %} {{picture.as_p}}
            </div>

            <div class="text-center">
              <button class="btn btn-outline-danger">
                <a
                  href="{% url 'review:posts' %}"
                  style="color: inherit; text-decoration: none"
                  >Retour</a
                >
              </button>
              {% if tickets%}
              <button class="btn btn-outline-success" type="submit">
                Modifier
              </button>
              {% endif %}
            </div>
          </form>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock main_content %}

review/templates/review/posts.html
{% extends '_base.html' %} {% load static %}
{% block main_content %}

<div class="container col-12 col-md-9 col-lg-6 p-2 borderTitle">
  <div class="row">
    <div class="jumbotron text-center">
      <h1>LITReview - Mes Posts</h1>
      <p>Bonjour, {{user.username}} !</p>
      {% if user.profile_photo %}

      <img src="{% get_media_prefix %}{{user.profile_photo}}" width="150px" />
      <div class="text-center">
        <button class="m-2 btn btn-outline-primary" type="submit">
          <a
            href="{% url 'authentication:user_picture' %}"
            style="color: inherit; text-decoration: none"
            >Modifier sa photo</a
          >
        </button>
      </div>
      {% else %}
      <p>Vous n'avez pas encore de photos de profil</p>
      <div class="text-center">
        <button class="m-2 btn btn-outline-primary" type="submit">
          <a
            href="{% url 'authentication:user_picture' %}"
            style="color: inherit; text-decoration: none"
            >Ajouter sa photo</a
          >
        </button>
      </div>
      {% endif %}
      <div class="text-center">
        <button class="m-2 btn btn-outline-primary" type="submit">
          <a
            href="{% url 'authentication:password_change' %}"
            style="color: inherit; text-decoration: none"
            >Modifier son mot de passe</a
          >
        </button>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row my-3 d-flex justify-content-around">
    <div class="">
      {% for ticket in tickets %}
        {% if ticket.id in reviews_link_tickets%} 
          {% for review in reviews %}
            {% if ticket.id == review.ticket_id %}
              {% include "review/partials/_post_review_with_ticket.html" %}
            {% endif %}
          {% endfor %} 
          {% include "review/partials/_post_ticket_with_review.html" %} 
        {% else %}
          {% if ticket.user_id == request.user.id %} 
            {% include "review/partials/_post_ticket_without_review.html" %} 
          {% endif %} 
        {% endif %} 
      {% endfor %}
    </div>
  </div>
</div>

{% endblock main_content %}

review/templates/review/read_ticket.html
{% extends '_base.html' %} {% load static %} {% block main_content %}
<div class="container col-12 col-md-9 col-lg-6 m-auto p-2 borderTitle">
  <div class="row">
    <div class="jumbotron text-center">
      <h1>LITReview - Affichage du Ticket #{{ticket.id}}</h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="m-3 p-5 bg-light">
      {% if ticket %}
      <div>
        {% if request.user.id == ticket.user.id%}
        <p>Vous avez demandé une critique</p>
        {%else%}
        <p>{{ticket.user}} a demandé une critique</p>
        {% endif%}
        <a
          href="{% url 'review:read_ticket' number_ticket %}"
          style="color: inherit; text-decoration: none"
        >
          <h3 class="text-primary">
            Ticket #{{ ticket.id }} : {{ ticket.title }}
          </h3></a
        >
        <p class="text-end">Date de demande : {{ticket.time_created}}</p>

        <div class="border border-primary border-3 p-4 m-3">
          {% if ticket.image %}
          <img src="{{ ticket.image.url }}" width="100px" />
          {% endif %}
          <p class="text-primary m-3">Description de la demande :</p>
          <p>{{ ticket.description }}</p>
          {% if request.user.id == ticket.user_id%}
          <div class="text-end">
            <button class="btn btn-outline-primary">
              <a
                href="{% url 'review:modify_ticket' ticket.id %}"
                style="color: inherit; text-decoration: none"
                >Modifier
              </a>
            </button>
            <button class="btn btn-outline-danger">
              <a
                href="{% url 'review:delete_ticket' ticket.id %}"
                style="color: inherit; text-decoration: none"
                >Supprimer
              </a>
            </button>
          </div>
          {% endif %}
        </div>

        {% if ticket.review %}
        <div class="border border-success border-3 p-4 m-3">
          {% if request.user.id == review.user_id %}
          <p>Vous avez publié une critique</p>
          {% else %}
          <p>{{review.user_id}} a publié une critique</p>
          {% endif %}
          <h3 class="text-success">
            {{review.headline }} - {% if review.rating == 0 %} {%endif%}
            <!---->
            {% if review.rating == 1 %}⭐️{%endif%}
            <!---->
            {% if review.rating == 2 %}⭐️⭐️{% endif%}
            <!---->
            {% if review.rating == 3 %}⭐️⭐️⭐️{% endif%}
            <!---->
            {% if review.rating == 4 %}⭐️⭐️⭐️⭐️{% endif%}<!---->
            {% if review.rating == 5 %}⭐️⭐️⭐️⭐️⭐️{% endif%}
          </h3>
          <div class="border border-success border-3 p-4 m-3">
            <p class="text-primary m-3">Description de la critique :</p>
            <p>{{ review.body }}</p>
          </div>
          {% if request.user.id == review.user_id %}
          <div class="text-end">
            <button class="btn btn-outline-success">
              <a
                href="{% url 'review:modify_review' review.id %}"
                style="color: inherit; text-decoration: none"
                >Modifier
              </a>
            </button>
            <button class="btn btn-outline-danger">
              <a
                href="{% url 'review:delete_review' review.id %}"
                style="color: inherit; text-decoration: none"
                >Supprimer
              </a>
            </button>
          </div>
          {% endif %}
        </div>
        {% endif %}
        <div class="m-4 pt-5 d-flex flex-row justify-content-around">
          <div class="">
            <button class="btn btn-outline-success">
              <a
                href="javascript:history.back()"
                style="color: inherit; text-decoration: none"
                >Retour</a
              >
            </button>
          </div>
          <div class="">
            {%if not review%}
            <button class="btn btn-outline-success">
              <a
                href="{% url 'review:create_new_review_for_ticket' number_ticket %}"
                style="color: inherit; text-decoration: none"
                >Créer une critique</a
              >
            </button>
            {% endif%}
          </div>
        </div>
      </div>
      {% else %}
      <p>Il n'y a pas de N° de Ticket associé - ticket supprimé</p>

      <div class="text-center">
        <button class="btn btn-outline-success">
          <a
            href="javascript:history.back()"
            style="color: inherit; text-decoration: none"
            >Retour</a
          >
        </button>
      </div>
      {% endif%}
    </div>
  </div>
</div>
{% endblock main_content %}