authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, PasswordChangeView
from . import views

app_name = 'authentication'
urlpatterns = [
    path('', LoginView.as_view(template_name='authentication/connexion.html',
         redirect_authenticated_user=True), name='connexion'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authentication/password_change.html',
        success_url='done/'), name='password_change'),
    path('password_change/done/', views.password_changed,
         name='password_change_done'),
    path("inscription/", views.inscription, name="inscription"),
    path("user_picture/", views.user_picture, name="user_picture"),
    path('deconnexion/', views.deconnexion, name="deconnexion"),
]

litreview_project/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include("review.urls", namespace='review')),
    path('', include("authentication.urls", namespace='authentication')),
]

review/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'review'
urlpatterns = [
    path('home/', views.flux, name='home'),
    path('create_new_review/', views.create_new_review,
         name='create_new_review'),
    path('create_new_ticket/', views.create_new_ticket,
         name='create_new_ticket'),
    path('create_new_review_for_ticket/<int:number_ticket>/',
         views.create_new_review_for_ticket,
         name='create_new_review_for_ticket'),
    path('create_new_ticket_and_review/',
         views.create_new_ticket_and_review,
         name='create_new_ticket_and_review'),

    path('delete_ticket/<int:number_ticket>/',
         views.delete_ticket, name='delete_ticket'),
    path('modify_ticket/<int:number_ticket>/',
         views.modify_ticket, name='modify_ticket'),
    path('ticket/<int:number_ticket>/', views.read_ticket, name='read_ticket'),

    path('delete_review/<int:number_review>/',
         views.delete_review, name='delete_review'),
    path('modify_review/<int:number_review>/',
         views.modify_review, name='modify_review'),

    path('flux/', views.flux, name='flux'),
    path('follow/', views.follow, name='follow'),
    path('posts/', views.posts, name='posts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image


class User(AbstractUser):
    profile_photo = models.ImageField(
        upload_to='profile/', verbose_name='Photo de profil', null=True)

    IMAGE_MAX_SIZE = (300, 300)

    def resize_image(self):
        if self.profile_photo:
            profile_photo = Image.open(self.profile_photo)
            profile_photo.thumbnail(self.IMAGE_MAX_SIZE)
            profile_photo.save(self.profile_photo.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from . import users_form


def deconnexion(request):
    logout(request)
    return redirect('authentication:connexion')


def connexion(request):
    form = users_form.LoginForm()
    message = ''
    color = ""
    if request.method == 'POST':
        form = users_form.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                return redirect("review:home")
            else:
                message = 'Identifiants invalides !'
                color = "text-danger"
    context = {"form": form, "message": message, "color": color}
    return render(request, 'authentication/connexion.html', context)


def inscription(request):
    form = users_form.SignupForm()
    if request.method == 'POST':
        form = users_form.SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("review:home")
    context = {'form': form}
    return render(request, 'authentication/inscription.html', context)


@login_required
def user_picture(request):
    form = users_form.UserPictureForm(instance=request.user)
    if request.method == 'POST':
        form = users_form.UserPictureForm(
            request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('review:flux')
    context = {'form': form}
    return render(request, 'authentication/user_picture.html', context)


def password_changed(request):
    return render(request, 'authentication/password_change_done.html',)

authentication/templates/authentication/connexion.html
{% extends '_base.html' %} {% block main_content %}

<div class="container col-12 col-md-9 col-lg-6 borderTitle">
  <div class="row">
    <div class="jumbotron text-center">
      <h1>Bienvenue sur LITReview</h1>
      <p>Vous cherchez une critique littéraire ? demandez-la !</p>
    </div>
  </div>
</div>

<div class="container col-12 my-4">
  <div
    class="
      row
      m-auto
      d-flex
      flex-row
      justify-content-around
      align-content-around
      flex-wrap
    "
  >
    <div
      class="
        borderLeft
        m-2
        col-11 col-md-5
        p-5
        text-center
        d-flex
        flex-column
        justify-content-around
        align-content-around
      "
    >
      <h2>Inscrivez-vous maintenant</h2>

      <a
        style="text-decoration: none; color: inherit"
        href="{% url 'authentication:inscription' %}"
        class="btn btn-warning m-auto"
        >Inscription</a
      >
    </div>
    <div class="borderLeft col-11 col-md-5 p-3 text-center">
      <h2>Déjà membre ? <br />Alors Connectez-vous !</h2>
      <p class="{{color}}">{{ message }}</p>
      <form method="post">
        {{ form.as_p }} {% csrf_token %}
        <button type="submit" class="btn btn-warning">Se connecter</button>
      </form>
    </div>
  </div>
</div>

{% endblock main_content %}

authentication/templates/authentication/inscription.html
{% extends '_base.html' %} {% block main_content %}

<div class="container">
  <div class="row">
    <div class="my-4 d-flex flex-row justify-content-center">
      <div class="col-12 col-md-10 col-lg-8 borderLeft">
        <h1 class="text-center">Inscrivez-vous maintenant</h1>
        <div class="m-auto p-3">
          {% if form.errors %} {{ form.errors }} {% endif %}
          <form method="post">
            {{ form.as_p }} {% csrf_token %}
            <div class="text-center">
              <button class="btn btn-outline-danger" type="submit">
                <a
                  href="{% url 'authentication:connexion' %}"
                  style="color: inherit; text-decoration: none"
                  >Retour</a
                >
              </button>
              <button class="btn btn-outline-success" type="submit">
                S’inscrire
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}

authentication/templates/authentication/password_change.html
{% extends '_base.html' %} {% block main_content %}

<div class="container">
  <div class="row">
    <div class="my-4 d-flex flex-row justify-content-center">
      <div class="col-12 col-md-10 col-lg-8 borderLeft">
        <h1 class="text-center">Modifier son mot de passe :</h1>
        <div class="m-auto p-3">
          {% if form.errors %} {{ form.errors }} {% endif %}
          <form method="post">
            {{ form.as_p }} {% csrf_token %}
            <div class="text-center">
              <button class="btn btn-outline-danger" type="submit">
                <a
                  href="{% url 'authentication:connexion' %}"
                  style="color: inherit; text-decoration: none"
                  >Retour</a
                >
              </button>
              <button class="btn btn-outline-success" type="submit">
                Modifier
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}

authentication/templates/authentication/password_change_done.html
{% extends '_base.html' %} {% block main_content %}

<div class="container">
  <div class="row">
    <div class="my-4 d-flex flex-row justify-content-center">
      <div class="col-12 col-md-10 col-lg-8 borderLeft">
        <h1 class="text-center">Modifier son mot de passe :</h1>
        <div class="m-auto p-3">
          <p>Vous avez changé votre mot de passe avec succès !</p>

          <div class="text-center">
            <button class="btn btn-outline-danger" type="submit">
              <a
                href="{% url 'review:posts' %}"
                style="color: inherit; text-decoration: none"
                >Revenir à la page d’accueil</a
              >
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}

authentication/templates/authentication/user_picture.html
{% extends '_base.html' %} {% block main_content %}

<div class="container">
  <div class="row">
    <div class="my-4 d-flex flex-row justify-content-center">
      <div class="col-12 col-md-10 col-lg-8 borderLeft">
        <h1 class="text-center">Modifier sa photo de profil :</h1>
        <div class="m-auto p-3">
          {% if form.errors %} {{ form.errors }}
          <hr />
          {% endif %}
          <form method="post" enctype="multipart/form-data">
            {{ form.as_p }} {% csrf_token %}
            <div class="text-center">
              <button class="btn btn-outline-danger" type="submit">
                <a
                  href="{% url 'authentication:connexion' %}"
                  style="color: inherit; text-decoration: none"
                  >Retour</a
                >
              </button>
              <button class="btn btn-outline-success" type="submit">
                Modifier
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}