authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, PasswordChangeView
from . import views

app_name = 'authentication'
urlpatterns = [
    path('', LoginView.as_view(template_name='authentication/connexion.html',
         redirect_authenticated_user=True), name='connexion'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authentication/password_change.html',
        success_url='done/'), name='password_change'),
    path('password_change/done/', views.password_changed,
         name='password_change_done'),
    path("inscription/", views.inscription, name="inscription"),
    path("user_picture/", views.user_picture, name="user_picture"),
    path('deconnexion/', views.deconnexion, name="deconnexion"),
]

litreview_project/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include("review.urls", namespace='review')),
    path('', include("authentication.urls", namespace='authentication')),
]

review/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'review'
urlpatterns = [
    path('home/', views.flux, name='home'),
    path('create_new_review/', views.create_new_review,
         name='create_new_review'),
    path('create_new_ticket/', views.create_new_ticket,
         name='create_new_ticket'),
    path('create_new_review_for_ticket/<int:number_ticket>/',
         views.create_new_review_for_ticket,
         name='create_new_review_for_ticket'),
    path('create_new_ticket_and_review/',
         views.create_new_ticket_and_review,
         name='create_new_ticket_and_review'),

    path('delete_ticket/<int:number_ticket>/',
         views.delete_ticket, name='delete_ticket'),
    path('modify_ticket/<int:number_ticket>/',
         views.modify_ticket, name='modify_ticket'),
    path('ticket/<int:number_ticket>/', views.read_ticket, name='read_ticket'),

    path('delete_review/<int:number_review>/',
         views.delete_review, name='delete_review'),
    path('modify_review/<int:number_review>/',
         views.modify_review, name='modify_review'),

    path('flux/', views.flux, name='flux'),
    path('follow/', views.follow, name='follow'),
    path('posts/', views.posts, name='posts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

litreview_project/templates/partials/_footer.html
{% block footer %}
<div
  class="container-fluid bg-dark"
  style="
    background-color: #ffffff;
    position: fixed;
    bottom: -1px;
    width: 100%;
    z-index: 1;
  "
>
  <div class="row">
    <div class="col text-center text-light">LITReview - 2021</div>
  </div>
</div>

{% endblock %}

litreview_project/templates/partials/_header.html
{% load static %} {% block header %}

<!-- NAVBAR -->
<div
  id="divNavBar"
  class="bg-light mb-3 sticky-top shadow d-flex flew-row justify-content-center"
>
  <nav
    class="
      col
      navbar navbar-expand-md navbar-light
      d-flex
      justify-content-center
    "
  >
    <div class="col-4 text-center">
      <img
        class="navbar-brand"
        src="{% static 'litreview_project/img/logo_litreview.png' %}"
        alt="Logo de LITReview"
        data-toggle="tooltip"
        data-placement="bottom"
        title="Le logo de Logo de LITReview"
        width="45"
      />
    </div>
    {% if user.is_authenticated %}
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div
      id="navbarSupportedContent"
      class="collapse navbar-collapse text-center m-auto"
    >
      <ul
        class="
          col-sm-6 col-md-9
          navbar-nav
          d-flex
          justify-content-center
          m-auto
        "
      >
        <li class="nav-item mx-1 shadow">
          <a class="nav-link" href="{% url 'review:flux' %}"> Flux </a>
        </li>
        <li class="nav-item mx-1 shadow">
          <a class="nav-link" href="{% url 'review:posts' %}"> Posts </a>
        </li>
        <li class="nav-item mx-1 shadow">
          <a class="nav-link" href="{% url 'review:follow' %}"> Abonnements </a>
        </li>
        <li class="nav-item mx-1 shadow">
          <a class="nav-link" href="{% url 'authentication:deconnexion' %}">
            Se déconnecter
          </a>
        </li>
      </ul>
    </div>
    {% endif %}
  </nav>
</div>

{% endblock %}