authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, PasswordChangeView
from . import views

app_name = 'authentication'
urlpatterns = [
    path('', LoginView.as_view(template_name='authentication/connexion.html',
         redirect_authenticated_user=True), name='connexion'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authentication/password_change.html',
        success_url='done/'), name='password_change'),
    path('password_change/done/', views.password_changed,
         name='password_change_done'),
    path("inscription/", views.inscription, name="inscription"),
    path("user_picture/", views.user_picture, name="user_picture"),
    path('deconnexion/', views.deconnexion, name="deconnexion"),
]

litreview_project/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include("review.urls", namespace='review')),
    path('', include("authentication.urls", namespace='authentication')),
]

review/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'review'
urlpatterns = [
    path('home/', views.flux, name='home'),
    path('create_new_review/', views.create_new_review,
         name='create_new_review'),
    path('create_new_ticket/', views.create_new_ticket,
         name='create_new_ticket'),
    path('create_new_review_for_ticket/<int:number_ticket>/',
         views.create_new_review_for_ticket,
         name='create_new_review_for_ticket'),
    path('create_new_ticket_and_review/',
         views.create_new_ticket_and_review,
         name='create_new_ticket_and_review'),

    path('delete_ticket/<int:number_ticket>/',
         views.delete_ticket, name='delete_ticket'),
    path('modify_ticket/<int:number_ticket>/',
         views.modify_ticket, name='modify_ticket'),
    path('ticket/<int:number_ticket>/', views.read_ticket, name='read_ticket'),

    path('delete_review/<int:number_review>/',
         views.delete_review, name='delete_review'),
    path('modify_review/<int:number_review>/',
         views.modify_review, name='modify_review'),

    path('flux/', views.flux, name='flux'),
    path('follow/', views.follow, name='follow'),
    path('posts/', views.posts, name='posts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

review/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models
from django.utils import timezone
from PIL import Image


class Ticket(models.Model):
    title = models.CharField(max_length=128, verbose_name="Titre du Ticket")
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    time_created = models.DateTimeField(
        default=timezone.now)

    IMAGE_MAX_SIZE = (300, 300)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            self.resize_image()


class Review(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        verbose_name="Note", help_text="Note attribuée à la critique")
    headline = models.CharField(
        max_length=128,
        verbose_name="Titre de Critique")
    body = models.TextField(max_length=8192, blank=True,
                            verbose_name="Commentaire")
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(
        default=timezone.now)


class UserFollows(models.Model):
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name="following")
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name="followed_by")

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = ('user', 'followed_user')

review/forms.py
from django import forms

from . import models as models_review


class TicketForm(forms.ModelForm):
    title = forms.CharField(label="Titre", widget=forms.TextInput(
        {"class": "form-control", "placeholder": "Mettez le titre du livre"}))
    description = forms.CharField(label="Description", widget=forms.Textarea(
        {"class": "form-control", "placeholder": "Mettez le titre du livre"}))

    class Meta:
        model = models_review.Ticket
        fields = ['title', 'description', 'image']


class ModifTicketTitleDescription(forms.ModelForm):
    title = forms.CharField(label="Titre", widget=forms.TextInput(
        {"class": "form-control", "placeholder": "Mettez le titre du livre"}))
    description = forms.CharField(label="Description", widget=forms.Textarea(
        {"class": "form-control", "placeholder": "Mettez le titre du livre"}))

    class Meta:
        model = models_review.Ticket
        fields = ['title', 'description']


class ModifPicture(forms.ModelForm):

    class Meta:
        model = models_review.Ticket
        fields = ['image']


class ReviewForm(forms.ModelForm):

    headline = forms.CharField(label="Titre de la critique",
                               widget=forms.TextInput(
                                {"class": "form-control",
                                 "placeholder": "Mettez le titre de votre "
                                                "critique"}
                               )
                               )
    RATING_CHOICES = [(0, "-0"), (1, '- 1'), (2, '-2'),
                      (3, '-3'), (4, '-4'), (5, '-5')]
    rating = forms.ChoiceField(
        choices=RATING_CHOICES, widget=forms.RadioSelect, label="Votre note")
    body = forms.CharField(label="Votre critique", widget=forms.Textarea(
        {"class": "form-control",
         "placeholder": "Mettez le détails de votre critique"}))

    class Meta:
        model = models_review.Review
        fields = ["headline", 'rating', 'body']


class UserFollowsForm(forms.ModelForm):
    class Meta:
        model = models_review.UserFollows
        fields = ["user"]


class UserRemoveFollowsForm(forms.ModelForm):
    class Meta:
        model = models_review.UserFollows
        fields = ["user"]

review/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required


from . import forms, models
from authentication import models as auth_models


@login_required
def create_new_ticket(request):
    form = forms.TicketForm()
    if request.method == 'POST':
        form = forms.TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect('review:flux')
    context = {'form': form}
    return render(request, 'review/create_new_ticket.html', context)


@login_required
def create_new_ticket_and_review(request):
    ticket_form = forms.TicketForm()
    review_form = forms.ReviewForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        review_form = forms.ReviewForm(request.POST)
        if all([ticket_form.is_valid(), review_form.is_valid()]):
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            review = review_form.save(commit=False)
            review.ticket_id = ticket.id
            review.user = request.user
            review.save()
            return redirect('review:flux')
    context = {'ticket_form': ticket_form, "review_form": review_form}
    return render(request, 'review/create_new_ticket_and_review.html', context)


@login_required
def create_new_review_for_ticket(request, number_ticket):
    tickets = models.Ticket.objects.filter(id=number_ticket)
    form = forms.ReviewForm()
    if request.method == 'POST':
        form = forms.ReviewForm(
            request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user_id = request.user.id
            review.ticket_id = number_ticket
            review.save()
            return redirect('review:flux')
    context = {'form': form, "tickets": tickets}
    return render(request, 'review/create_new_review.html', context)


@login_required
def create_new_review(request):
    return render(request, 'review/create_new_review.html')


@login_required
def follow(request):
    all_followed_id = list(models.UserFollows.objects.filter(
        user=request.user.id).values_list('followed_user_id', flat=True))
    all_followed_id.append(request.user.id)
    all_users_to_be_followed = auth_models.User.objects.all().exclude(
        id__in=all_followed_id)
    user_form = forms.UserFollowsForm()
    remove_user_followed_form = forms.UserRemoveFollowsForm()
    user_followed_by_request_user = models.UserFollows.objects.filter(
        user=request.user.id)
    request_user_followed_by_other = models.UserFollows.objects.filter(
        followed_user=request.user.id)
    context = {"user_form": user_form,
               "remove_user_followed_form": remove_user_followed_form,
               "all_users_to_be_followed": all_users_to_be_followed,
               "user_followed_by_request_user": user_followed_by_request_user,
               "request_user_followed_by_other": request_user_followed_by_other
               }

    if request.method == 'POST':
        user_form = forms.UserFollowsForm(request.POST)
        remove_user_followed_form = forms.UserRemoveFollowsForm(request.POST)
        if user_form.is_valid():
            follow = models.UserFollows.objects.filter(
                user_id=request.user.id,
                followed_user=request.POST.get("user")[0])
            if not follow:
                follow = models.UserFollows.objects.create()
                follow.user_id = request.user.id
                follow.followed_user_id = str(request.POST.get("user")[0])
                follow.save()

        if request.POST.get("user_followed_to_delete"):
            followed = models.UserFollows.objects.filter(
                user_id=request.user.id,
                followed_user=request.POST.get("user_followed_to_delete")[0])
            followed.delete()
        return redirect("review:follow")
    return render(request, 'review/follow.html', context)


@ login_required
def flux(request):
    all_followed = models.UserFollows.objects.filter(
        user_id=request.user.id).values_list('followed_user_id', flat=True)
    all_followed = list(all_followed)
    all_followed.append(request.user.id)

    reviews = models.Review.objects.filter(
        user_id__in=all_followed)
    reviews_link_tickets = models.Review.objects.filter(
        user_id__in=all_followed).values_list('ticket_id', flat=True)
    tickets = models.Ticket.objects.filter(
        user_id__in=all_followed) | models.Ticket.objects.filter(
        id__in=reviews_link_tickets)
    tickets = tickets.order_by("-id")
    context = {"tickets": tickets, "reviews": reviews,
               "reviews_link_tickets": reviews_link_tickets}
    return render(request, 'review/flux.html', context=context)


@ login_required
def posts(request):
    reviews = models.Review.objects.filter(
        user_id=request.user.id).values()
    reviews_link_tickets = models.Review.objects.filter(
        user_id=request.user.id).values_list('ticket_id', flat=True)
    tickets = models.Ticket.objects.filter(
        user_id=request.user.id) | models.Ticket.objects.filter(
        id__in=reviews_link_tickets)
    tickets = tickets.order_by("-id")
    context = {"tickets": tickets, "reviews": reviews,
               "reviews_link_tickets": reviews_link_tickets}
    return render(request, 'review/posts.html', context)
# GESTION TICKETS


@ login_required
def modify_ticket(request, number_ticket):
    context = {"number_ticket": number_ticket}
    tickets = get_object_or_404(models.Ticket, id=number_ticket)
    if request.user.id == tickets.user_id:
        form = forms.ModifTicketTitleDescription(instance=tickets)
        context["form"] = form
        picture = forms.ModifPicture(instance=tickets)
        context["picture"] = picture
        context["tickets"] = tickets
        if request.method == 'POST':
            form = forms.ModifTicketTitleDescription(
                request.POST)
            if form.is_valid():
                tickets.title = form.cleaned_data["title"]
                tickets.description = form.cleaned_data["description"]
                tickets.save()

                picture = forms.ModifPicture(request.POST, request.FILES)
                if all([picture.is_valid()]):
                    new_picture = picture.save(commit=False)
                    tickets.image = new_picture.image
                    tickets.save()
                return redirect('review:posts')

    return render(request, 'review/modify_ticket.html', context)


@ login_required
def read_ticket(request, number_ticket):
    ticket = get_object_or_404(models.Ticket, id=number_ticket)
    context = {"ticket": ticket, "number_ticket": number_ticket}
    review = models.Review.objects.filter(ticket_id=number_ticket)
    if review:
        ticket.review = review[0]
        context["review"] = review[0]
    return render(request, 'review/read_ticket.html', context)


@ login_required
def delete_ticket(request, number_ticket):
    context = {"number_ticket": number_ticket}
    ticket = get_object_or_404(models.Ticket, id=number_ticket)
    if ticket:
        context["ticket"] = ticket
    review = models.Review.objects.filter(ticket_id=number_ticket)
    if review:
        context["review"] = review

    if request.method == 'POST':
        ticket = get_object_or_404(
            models.Ticket, id=number_ticket)
        review = models.Review.objects.filter(ticket_id=number_ticket)
        if review:
            review.delete()
        if ticket:
            ticket.delete()
        return redirect("review:posts")
    return render(request, 'review/delete_ticket.html', context)


# GESTION REVIEW


@ login_required
def modify_review(request, number_review):
    context = {"number_review": number_review}
    reviews = get_object_or_404(models.Review, id=number_review)
    ticket = get_object_or_404(models.Ticket, id=reviews.ticket_id)
    if request.user.id == reviews.user_id:
        form = forms.ReviewForm(instance=reviews)
        if request.method == 'POST':
            form = forms.ReviewForm(
                request.POST, instance=reviews)
            if form.is_valid():
                form.save()
                return redirect('review:flux')
        context["form"] = form
        if ticket:
            context["ticket"] = ticket
        if reviews:
            context["reviews"] = reviews
    return render(request, 'review/modify_review.html', context)


@ login_required
def delete_review(request, number_review):
    review = get_object_or_404(models.Review, id=number_review)
    ticket = get_object_or_404(models.Ticket, id=review.ticket_id)
    ticket.review = review
    if request.method == 'POST':
        review = get_object_or_404(models.Review, id=number_review)
        review.delete()
        return redirect("review:posts")
    context = {"review": review, "ticket": ticket}
    return render(request, 'review/delete_review.html', context)

litreview_project/review/templates/review/_base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
      crossorigin="anonymous"
    />
    <link href="{% static 'review/css/style.css' %}" rel="stylesheet" />

    <title>LITReview</title>
  </head>

  <style>
    body {
      background-image: url("{% static 'review/img/typewriter-801921_1920.jpg' %}");
      background-attachment: fixed;
      background-repeat: no-repeat;
      background-size: cover;
    }
  </style>
  <body class="bg-secondary">
    {% include "review/_header.html" %} {% block main_content %} {% endblock %}
    {% include "review/_footer.html" %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://unpkg.com/htmx.org@1.6.0"
      integrity="sha384-G4dtlRlMBrk5fEiRXDsLjriPo8Qk5ZeHVVxS8KhX6D7I9XXJlNqbdvRlp9/glk5D"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

litreview_project/review/templates/review/_header.html
{% load static %} {% block header %}
<div class="container-fluid mb-4">
  <div class="row">
    <!-- NAVBAR -->
    <div
      id="divNavBar"
      class="
        bg-light
        sticky-top
        shadow
        d-flex
        flex-column
        justify-content-center
      "
    >
      <nav
        class="
          navbar
          m-1
          navbar-expand-md navbar-light
          d-flex
          flex-row
          justify-content-around
          align-content-around
        "
      >
        <img
          class="navbar-brand"
          src="{% static 'review/img/logo_litreview.png' %}"
          alt="Logo de LITReview"
          width="5%"
          data-toggle="tooltip"
          data-placement="bottom"
          title="Logo de LITReview"
        />

        {%  if user.is_authenticated %}
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarContent"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbarContent" class="collapse navbar-collapse">
          <ul class="navbar-nav m-auto">
            <li class="nav-item active m-1 shadow">
              <a class="nav-link" href="{% url 'review:home' %}"> Accueil </a>
            </li>

            <li class="nav-item m-1 shadow">
              <a class="nav-link" href="#"> Flux </a>
            </li>
            <li class="nav-item m-1 shadow">
              <a class="nav-link" href="#"> Posts </a>
            </li>
            <li class="nav-item m-1 shadow">
              <a class="nav-link" href="#"> Abonnements </a>
            </li>
            <li class="nav-item m-1 shadow">
              <a class="nav-link" href="{% url 'review:deconnexion' %}">
                Se déconnecter
              </a>
            </li>
          </ul>
        </div>
        {% endif %}
      </nav>
    </div>
  </div>
</div>

{% endblock %}

litreview_project/review/templates/review/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
      crossorigin="anonymous"
    />

    <title>LITReview</title>
  </head>
  <body class="bg-secondary">
    {% include "review/header.html" %} {% block main_content %} {% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

litreview_project/review/templates/review/connexion.html
{% extends 'review/_base.html' %} {% block main_content %}

<div class="container p-5 bg-light">
  <div class="row">
    <div class="jumbotron text-center">
      <h1>Bienvenue sur LITReview</h1>
      <p>Vous cherchez une critique littéraire ? demandez-la !</p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="my-5 py-5 d-flex flex-row justify-content-around">
      <div class="col-5 py-5 bg-light text-center">
        <h2>Inscrivez-vous maintenant</h2>
        <button type="button" class="btn btn-warning">
          <a
            style="text-decoration: none; color: inherit"
            href="{% url 'review:inscription' %}"
            >Inscription</a
          >
        </button>
      </div>
      <div class="col-5 p-3 bg-light text-center">
        <h2>Déjà membre ? <br />Alors Connectez-vous !</h2>
        <p class="{{color}}">{{ message }}</p>
        <form method="post">
          {{ form.as_p }} {% csrf_token %}
          <button type="submit" class="btn btn-warning">Se connecter</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock main_content %}

litreview_project/review/templates/review/inscription.html
{% extends 'review/_base.html' %} {% block main_content %}

<div class="container">
  <div class="row">
    <div class="my-4 d-flex flex-row justify-content-center">
      <div class="col-6 bg-light">
        <h1 class="text-center">Inscrivez-vous maintenant</h1>
        <div class="m-auto p-3">
          {% if form.errors %} {{ form.errors }} {% endif %}
          <form method="post">
            {{ form.as_p }} {% csrf_token %}
            <div class="text-center">
              <button class="btn btn-outline-danger" type="submit">
                <a
                  href="{% url 'review:connexion' %}"
                  style="color: inherit; text-decoration: none"
                  >Retour</a
                >
              </button>
              <button class="btn btn-outline-success" type="submit">
                S’inscrire
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}